### ISSUE TITLE
Add stop parsing symbol `--%` to the grammar

### ISSUE THREAD

**Issue by jrsconfitto** [SublimeText/PowerShell#104]
Not super important.

In the atom language tests (jugglingnutcase/language-powershell#36) the tests are failing on `--%`. We should add it at some point. Here's the [about_Escape_Characters spec](https://technet.microsoft.com/en-us/library/hh847755.aspx) which contains this stuff under the "Stop parsing symbol".

**Comment by michaelblyons** [comment]
Fixed by #165
