### ISSUE TITLE
create script to publish package to 'master'

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PowerShell#116]
MUST:

- [x] remove unneeded files

~~- [ ] commit changes~~

**Comment by guillermooo** [comment]
@vors I think we'd agreed on using 'master' as the release channel? So basically we only need to deleted  dev files and push to master, right?

**Comment by vors** [comment]
Yep. Uh, it would be also cool to publish it asappveyor artifact on each build. 

Sent from Outlook




On Wed, Mar 25, 2015 at 1:57 PM -0700, "Guillermo López-Anglada" <notifications@github.com> wrote:












Closed #116.

**Comment by guillermooo** [comment]
Tried a very basic thing, but I don't really like it. We need to find a better way of publishing versions.
