### ISSUE TITLE
Here String is breaking syntax

### ISSUE THREAD

**Issue by noesberger** [SublimeText/PowerShell#118]
Hi

When I have a Powershell here string
$x = @"
"blala
balal
balal" 
"@

and the last row is inlined ("@) with space or tab, it's breaking the highlighting for the code that is following.

Does anyone else have the same error?

**Comment by vors** [comment]
Do you mean

```powershell
$x = @"
"blala
balal
balal" 
    "@
```

?

**Comment by Jaykul** [comment]
inlined or indented?

If it's indented like @vors wrote, that's not a valid here-string.

**Comment by noesberger** [comment]
Sorry, indented.
Ok, then it's my fault. Thanks for your fast reply
