### ISSUE TITLE
tracking new syntax def features in ST

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PowerShell#123]
http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17892

**Comment by guillermooo** [comment]
The new syntax definition format used by Sublime Text can fully parse LL(1) grammars. Assuming that PowerShell's syntax isn't LL(1), we should try to figure out which constructs are most useful to parse more thoroughly.

At the very least, the new syntax def should be as comprehensive as the existing one.

I'll create a new branch and start working on the new syntax definition.

However, PowerShell has evolved a lot and I'm not really up-to-date with all the new stuff, so I'll start with the parts I know better and we can expand it from there.

**Comment by vors** [comment]
Closing in favor of https://github.com/PowerShell/EditorSyntax
