### ISSUE TITLE
`default` should be a keyword inside a switch

### ISSUE THREAD

**Issue by vors** [SublimeText/PowerShell#125]
![image](https://cloud.githubusercontent.com/assets/816680/6989525/49cca4f0-da11-11e4-8a82-509351464591.png)

![image](https://cloud.githubusercontent.com/assets/816680/6989539/5e841176-da11-11e4-8a17-640b61a300e1.png)

**Comment by guillermooo** [comment]
@vors Perhaps you've seen it --- a much more powerful lexer for grammars is in flight, including unit testing.

**Comment by vors** [comment]
Yes, I'm very excited about it. Does it have any story to convert it to tmLanguage, so atom and github can benefit from it?

**Comment by Jaykul** [comment]
and vs code, and visual studio, and ...

**Comment by vors** [comment]
Sort-of fixed in EditorSyntax: `default` is simply a keyword everywhere. Which is a better approach I think.
