### ISSUE TITLE
Build not working for powershell scripts #withFix

### ISSUE THREAD

**Issue by pixelrebirth** [SublimeText/PowerShell#129]
Here is the fix for it:

{
    "cmd": ["powershell.exe", "-noprofile", "-executionpolicy", "bypass", "$file"],
    "selector": "source.powershell"
}
# changed unrestricted to bypass based on comments below

**Comment by guillermooo** [comment]
@vors I wonder whether we should use "bypass" instead of "unrestricted"?

**Comment by pixelrebirth** [comment]
I agree that would be better, unrestricted is quick build mode for me-- bypass is more appropriate IMO

**Comment by vors** [comment]
I agree.

**Comment by pixelrebirth** [comment]
Works perfect still, of course. 

read-host doesnt however, but I think that is a limitation with sublime not being able to prompt correctly

**Comment by hermes369** [comment]
OK. I'll be the noob who asks where to put the above? I've tried creating a Powershell directory in \\users\me\appdata\roaming\sublime text 3\packages\powershell\Powershell.sublime-project and cloning into the packages directory only to see it deleted and editing the .sublime-project file both times the powershell directory gets removed on relaunch of Sublime Text.
Clearly I'm doing it wrong.

**Comment by pixelrebirth** [comment]
C:\Users\me\AppData\Roaming\Sublime Text 3\Packages\PowerShell-master\Support\Powershell.sublime-build
