### ISSUE TITLE
Not working under Linux.

### ISSUE THREAD

**Issue by mad-doctor** [SublimeText/PowerShell#13]
When sublime text is trying to load the plugin it gives the following error:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./setup.py", line 11, in <module>
    from distutils import log, dir_util, dep_util, file_util, archive_util
ImportError: No module named distutils

I've tried to include distutils folder from the default python install on my system to sublime text's python26.zip with no success.

Sublime Text 2.0.1 on Slackware 14.0 (kernel 3.2.29)

Update: It worked after I removed setup.py file.

**Comment by vors** [comment]
Can anybody check, is this issue still actual? cc @guillermooo 
I don't work on Linux right now.

**Comment by mad-doctor** [comment]
I've checked the issue both in sublime 2 and sumblime 3 (3065 build) on Arch Linux - no errors on startup, everything seems just fine.

**Comment by vors** [comment]
cool! Thank you

**Comment by guillermooo** [comment]
I must have removed the `setup.py` since we're now recommending to publish the files locally as a folder, not a `.sublime-package` archive.
