### ISSUE TITLE
Unable to install PowerShell package

### ISSUE THREAD

**Issue by roman-bl** [SublimeText/PowerShell#131]
Followed the instructions, but Sublime 3 couldn't find PowerShell package to install.  Tried to use Advanced Install Package, but with the same result. 
![image](https://cloud.githubusercontent.com/assets/4933359/8044965/3ba06fa8-0dfe-11e5-9ffa-7152e1403409.png)
![image](https://cloud.githubusercontent.com/assets/4933359/8044979/4f374a78-0dfe-11e5-861d-55cf6c9bbd1f.png)

Please advise!

**Comment by vors** [comment]
[Should be there](https://packagecontrol.io/packages/PowerShell).
It's in the [default package control channels](https://github.com/wbond/package_control_channel/blob/master/repository/p.json#L1201).

One thought: package control entry doesn't have explicit name. I assume, it should fetch the name from the repo url / description / etc. Maybe this logic was changed recently.

Can you, please open an issue in https://github.com/wbond/package_control_channel ?

**Comment by roman-bl** [comment]
Thanks for the quick reply.  There is already one open issue regarding many missing packages. So, I just left a comment there.  Interestingly enough, the issue is fresh (3h), so probably something resent that was introduced.

**Comment by vors** [comment]
@roman-bl can you try now?

**Comment by roman-bl** [comment]
Everything works. Closing the issue. :)
Thank you for help!
