### ISSUE TITLE
Complicated regex in ValidatePattern breaks the grammar

### ISSUE THREAD

**Issue by vors** [SublimeText/PowerShell#132]
``` powershell
Function Get-Domain
{
    [CmdletBinding()]
    param(
        [ValidatePattern('^(?=^.{1,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)')]
        [Parameter(ValueFromPipeline = $true)] # this line should not be highlighted as a string
        [string]$domain
    )
}
```

**Comment by godeater** [comment]
I have a fix for this, but I'm not sure where it should be sent - it seems various different editors use TextMate's language definition for Powershell, but I've never used TextMate (and can't, being as how I abhor Macs), so I can't text the fix there...

**Comment by vors** [comment]
Yes, this is the right place.
Atom, VSCode and GitHub uses the same grammar.

**Comment by vors** [comment]
Oh, apparently another comment was removed

**Comment by daviwil** [comment]
@godeater this is the right place :)

**Comment by godeater** [comment]
I removed the comment I put earlier as I found that the new grammar I had, although it didn't wreck the syntax highlighting through the rest of the buffer as the current one does, now only highlights on the first "variable=value" in a [Parameter( block.
I'm trying to work out if it's worth submitting it still as the lesser of two evils, or keep plugging away to see if I can fix the regex properly.

**Comment by daviwil** [comment]
Go ahead and fix it properly if you want to.  Definitely doesn't make sense to pull it in yet if it breaks other highlighting.

**Comment by vors** [comment]
This regex became pretty complicated, good luck.
You can share preview of your results with https://github-lightshow.herokuapp.com/

**Comment by godeater** [comment]
s/want to/can/ =/

After I noticed that problem, I kept looking at it all afternoon without much success.

Take a look at these and see which you think would be best to use.

With current grammar:
![before](https://cloud.githubusercontent.com/assets/1461/13017664/514f2528-d1bd-11e5-98bf-3f15f80aac29.png)

With new grammar:
![after](https://cloud.githubusercontent.com/assets/1461/13017666/5c442dca-d1bd-11e5-912e-e9c20d617471.png)

**Comment by vors** [comment]
@godeater send a PR with a reference to this issue, we can take a look together.

It always takes few hours to switch context to tmLanguage syntax, but I feel there were no releases for quite some time and GitHub's highlighting is out-of-date.

**Comment by godeater** [comment]
I've sent a pull request, but not sure if I've done it right or not.

**Comment by godeater** [comment]
I presume the decision was taken that this wasn't good enough?

**Comment by yokai117** [comment]
Was this ever resolved? I seem to be having the same issue at present and it's making it difficult to switch to atom for powershell.

**Comment by vors** [comment]
@godeater hey sorry for a very long reply time: completely slipped out of my radar. It looks like you sent https://github.com/SublimeText/PowerShell/pull/145 , right?

I think all maintainers just dropped ball here at the time, not that it was not good enough. Sorry for that.

**Comment by vors** [comment]
The plan was to move highlighting development to https://github.com/PowerShell/EditorSyntax but it stalled a little bit too.

**Comment by yokai117** [comment]
Thanks for the update.  Seems there are a few bugs related to syntax highlighting in there.  I'll see how they're progressing.
