### ISSUE TITLE
No syntax highlighting on Mac

### ISSUE THREAD

**Issue by sodacrackers** [SublimeText/PowerShell#136]
Does this plugin work on Mac, OS X 10.10 Yosemite?  I've followed the simple _Package Manager_ install instructions and tried copying the source to `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/` 

Even after restarting Sublime 3 I get no syntax highlighting for `ps1` extensions.  Same after settings them PowerShell under `View > Syntax > Open all as...`  

Many thanks.

**Comment by vors** [comment]
Going to close this one old install issue. I hope you found a solution, but if not please open a new issue.
