### ISSUE TITLE
Where-Object does not seem to highlight properly

### ISSUE THREAD

**Issue by dotps1** [SublimeText/PowerShell#139]
Using the following code the 'Where-Object' does not hightlight properly.

``` PowerShell
Get-Process | Where-Object -FilterScript {
    # do things
}
```

The 'Where' is identified but the '-Object' is not.

(Snippit from VSCode)
![image](https://cloud.githubusercontent.com/assets/1016996/11347346/f6c7fe9e-91ee-11e5-9e7a-306bf621092a.png)

Thanks.

**Comment by elpresidento** [comment]
It looks where-object still is not fixed
find
`<string>(?&lt;!\w)(?i:foreach-object)(?!\w)</string>`
to replace
`<string>(?&lt;!\w)(?i:foreach-object|where-object)(?!\w)</string>`
find
`|var|where(?!=-object)|while)`
to replace
`|var|where(?!-object)|while)`
Then where-object works fine.
