### ISSUE TITLE
"configuration" breaks Syntax Highlighting

### ISSUE THREAD

**Issue by bcrotty** [SublimeText/PowerShell#140]
![2015-11-23 12_56_30-photos](https://cloud.githubusercontent.com/assets/6155964/11347942/4baed212-91e9-11e5-97da-d9158884d43d.png)
"configuration" breaks syntax highlighting after it.

![2015-11-23 12_59_17-c__users_bcrotty_onedrive_script archive_select franchise network discovery ps1](https://cloud.githubusercontent.com/assets/6155964/11347945/4dd55e9e-91e9-11e5-97f2-af3522716667.png)
This is what it should look like.

**Comment by Jaykul** [comment]
This is fixed in dev already by https://github.com/SublimeText/PowerShell/pull/137
