### ISSUE TITLE
Adopt PowerShell Editor Services for IntelliSense, code navigations, etc in Windows

### ISSUE THREAD

**Issue by daviwil** [SublimeText/PowerShell#143]
I'm filing this issue to officially track the initial integration work for PowerShell Editor Services:

https://github.com/PowerShell/PowerShellEditorServices/

This will allow us to provide full IntelliSense support, code navigations, real-time syntax and semantic analysis, and script execution.  We'll also be able to provide an integrated REPL that's more like what you see in the ISE.

If anyone is opposed to integrating this in this package we can start a new one.  However I think it would be great to have it in the most commonly used PowerShell package!

**Comment by dzeleski** [comment]
Any chance on this being added soon?

**Comment by daviwil** [comment]
@dzeleski you can try a preview of the integration now but it might not be 100% reliable: https://github.com/SublimeText/PowerShell/pull/152.  I haven't had time to finish that work yet, but I'd certainly be interested in collaborating with others to finish it.

**Comment by dzeleski** [comment]
@daviwil For sure, ill be honest I've not tested any sublime plugins yet, is it as simple as just manually adding your commit as a repo in package control and installing that way?

**Comment by daviwil** [comment]
I don't think it will work with Package Control yet.  For now, follow these instructions to install it:

https://github.com/daviwil/SublimePowerShell/tree/editor-services#powershell-editor-services-integration-experimental

**Comment by dzeleski** [comment]
Oh perfect! Ill give this a shot tomorrow morning.

**Comment by dzeleski** [comment]
@daviwil Totally forgot about this, I just installed it using the instructions listed and it seems to be working. Thanks and sorry for the long delay. If I run into any issues ill open an issue.

**Comment by daviwil** [comment]
Very likely to not be working well (especially IntelliSense), hoping to get back to it at some point this year

**Comment by vors** [comment]
@daviwil is there any (partial)work we can sneak peak on?

**Comment by AmjadHD** [comment]
FWIW you can use the LSP package https://lsp.readthedocs.io/en/latest/#powershell

**Comment by deathaxe** [comment]
With LSP and LSP-PowerShellEditorServices packages being available that kind of task finally got obsolete or out of scope for this syntax definition package.
