### ISSUE TITLE
Coloring of variables is difficult to read

### ISSUE THREAD

**Issue by lzybkr** [SublimeText/PowerShell#147]
The default coloring of variables in VSCode is hard to read because the sigil is colored, but not the variable name.  This puts too much emphasis on the sigil and not the name.

I prefer having the sigil+variable colored, but not coloring anything would be better than the default.

Here is an example:

![image](https://cloud.githubusercontent.com/assets/2148248/13186115/59a17c76-d6f9-11e5-9e3e-8be2c22e193f.png)

**Comment by vors** [comment]
Moving this discussion to EditorSyntax https://github.com/PowerShell/EditorSyntax/issues/23

**Comment by omniomi** [comment]
@lzybkr please see my suggestion on PowerShell/EditorSyntax#23 and let me know what you think.
