### ISSUE TITLE
Powershell "Here-Strings" breaks syntax highlighting

### ISSUE THREAD

**Issue by jordigg** [SublimeText/PowerShell#151]
When using

```
$var = @"
Long text inside a variable
Long text inside a variable 2
Long text inside a variable 3
Long text inside a variable 4
"@
```

breaks syntax highlighting. Removing the first `@` fixes the highlight so I guess the error is how that @ is parsed.

Here a screen-shoot, with and without the first `@`
![Image of bug2](https://s31.postimg.org/llfto9x3f/sublime2.png) ![Image of bug1](https://s31.postimg.org/kun3ihuq3/sublime1.png)

**Comment by jordigg** [comment]
Now I saw #130 with the same problem. I see that it's because the indentation.
I have that code inside an `if` condition and that's why I use the indentation but it's still located at the same level of indentation as the opening "@".

**Comment by Jaykul** [comment]
That's not a bug, that's a feature.

Here strings in PowerShell have 3 character delimiters: at, quote, newline ---> newline, quote, at.

If there's whitespace between the newline and the quote, it's not valid powershell.

**Comment by vors** [comment]
Yes, thank you @Jaykul ! The indentation makes it invalid here-string.
