### ISSUE TITLE
OutputType Bracket Coloring

### ISSUE THREAD

**Issue by bcrotty** [SublimeText/PowerShell#154]
![2017-08-29 12_42_24-untitled script archive - sublime text](https://user-images.githubusercontent.com/6155964/29835472-ba2d854c-8cb7-11e7-8365-d2eef220f657.png)
Seems like `[System.String]` should be either all the same color or at least the brackets should be the same color.

There's still an issue when it's `String` instead of `System.String`

![2017-08-29 12_45_29-untitled script archive - sublime text](https://user-images.githubusercontent.com/6155964/29835545-fa18101e-8cb7-11e7-900c-c3a4049cfd5a.png)

**Comment by vors** [comment]
Looks like https://github.com/PowerShell/EditorSyntax handles it correctly.
We are planning to switch to their grammar soon.
Stay tuned.
