### ISSUE TITLE
Syntax highlight breaks on -Keyword parameter name

### ISSUE THREAD

**Issue by nanoant** [SublimeText/PowerShell#157]
When function parameter name is a keyword e.g. `-Function` then the syntax grammar gets confused, see example below for correct PowerShell script syntax with broken highlighting.

~~~powershell
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

function Prompt {
    Write-Host "[$(Get-Date -Format HH:mm:ss)] " -NoNewline -ForegroundColor Gray
    Write-Host $(Get-Location) -ForegroundColor Cyan
    return '> '
}
~~~

P.S. Even GitHub highlight breaks here :)

![image](https://user-images.githubusercontent.com/103067/35735928-a25fb350-0826-11e8-914f-5c1010bd5b10.png)

**Comment by xse** [comment]
Hi !
I have the same issue here : 

![2018-03-05 22_03_36-c__users_elouan_documents_windowspowershell_microsoft powershell_profile ps1 -](https://user-images.githubusercontent.com/183953/36999734-5eac9d7c-20c1-11e8-8be6-e3d823f14392.png)

As soon as i put a "(" after the buggy string it disappear :)

![2018-03-05 22_05_25-c__users_elouan_documents_windowspowershell_microsoft powershell_profile ps1 -](https://user-images.githubusercontent.com/183953/36999766-784a92e8-20c1-11e8-917e-ef94ba9a7a49.png)

Have a good day !

**Comment by vors** [comment]
Looks like https://github.com/PowerShell/EditorSyntax handles it correctly.
We are planning to switch to their grammar soon.
Stay tuned.
