### ISSUE TITLE
Not handling syntax correctly with docker-machine

### ISSUE THREAD

**Issue by mathew-ferry13** [SublimeText/PowerShell#158]
The command below is valid powershell syntax, but the highlighting does not believe the string is terminated:

`$ErrMsg = $(docker-machine ls --filter name=MachineName --format "{{.Error}}")`

**Comment by vors** [comment]
Looks like https://github.com/PowerShell/EditorSyntax handles it correctly.
We are planning to switch to their grammar soon.
Stay tuned.
