### ISSUE TITLE
Editor-Syntax

### ISSUE THREAD

**Issue by keith-hall** [SublimeText/PowerShell#161]
Hi,

I believe that the Editor-Syntax repository has had a few bug fixes upstream since it was copied for use in this repo. Would it make sense to have it as a git submodule, to make it easier to see which version is currently being used by this package, and easier to update this package to use the latest version?

**Comment by keith-hall** [comment]
Good question - Package Control just uses GitHub's zip download feature, so I guess it depends whether submodules are included in the zip or not. I will try to investigate this, thanks.

**Comment by keith-hall** [comment]
I have tested, at GitHub doesn't include submodules in the zip file. Your auto update script idea sounds like a good one.

**Comment by michaelblyons** [comment]
Could you (hard|soft|sym)link to the file that lives in the submodule such that GitHub adds it to the zip? And make a script to convert the file (if Git thinks the link is a file) into a link to be run after `clone`?

**Comment by vors** [comment]
Not sure is it possible or not. Currently there is no submodule because I don't know how sublime packages with submodules work.

**Comment by michaelblyons** [comment]
Obsoleted by #165?
