### ISSUE TITLE
Unable to find "PowerShell" package under Package Control

### ISSUE THREAD

**Issue by EmanueleCiriachi** [SublimeText/PowerShell#166]
- I press Ctrl + Shift + P (Windows machine);
- I select "Package Control: Install Package";
- I start typing Power... but no entry called "PowerShell" shows up, or anything containing the word "PowerShell" or other lower-case variants.

**Comment by michaelblyons** [comment]
I believe Package Control is running into some GitHub rate-limiting trouble. Try again in a little bit?

**Comment by mathieures** [comment]
The package was not available for me either, but I managed to install it through the "Advanced Install Package" sub-menu. It is case-sensitive though, so you have to type exactly "PowerShell".
