### ISSUE TITLE
Reindent problem with C#

### ISSUE THREAD

**Issue by stephen147** [SublimeText/PowerShell#168]
I assume that this controls the indentation for `.ps1` files so hopefully, this is the correct place to post this issue.

With Powershell I have this code:

```powershell
Function Get-ForegroundWindow {
  Add-Type @"
  using System; using System.Runtime.InteropServices; public class ClassGetForegroundWindow {
    [DllImport("user32.dll")]
    public static extern IntPtr GetForegroundWindow();
  }
"@
  return [ClassGetForegroundWindow]::GetForegroundWindow()
}

Get-ForegroundWindow
```

After reindenting it it appears to be:
```powershell
Function Get-ForegroundWindow {
  Add-Type @"
  using System; using System.Runtime.InteropServices; public class ClassGetForegroundWindow {
    [DllImport("user32.dll")]
    public static extern IntPtr GetForegroundWindow();
  }
  "@
  return [ClassGetForegroundWindow]::GetForegroundWindow()
}

Get-ForegroundWindow
```
This then fails to run as the `"@` is indented when it shouldn't.

**Comment by keith-hall** [comment]
I guess this repo lacks any tmPreferences files controlling indentation, so it uses the defaults. You'd want a `unindentedLinePattern` matching `"@` iirc.

**Comment by stephen147** [comment]
Oh, I didn't even think to see if there was one. I assumed there was.

Hopefully, this could get added as a rule if the person maintaining this repo sees this as it would be nice to be included out of the box.

**Comment by keith-hall** [comment]
Once #165 is merged and released, we will be able to officially close this issue as fixed 🎉
