### ISSUE TITLE
Manual Download and Install Package

### ISSUE THREAD

**Issue by blazer2k1** [SublimeText/PowerShell#174]
Hi, I would like to install it manually as I am having problems installing it via package manager.

Zipping and renaming it to `.sublime-package` does nothing, but it works on other github hosted sublime packages so far.

It would be nice to provide releases as manual download.

**Comment by michaelblyons** [comment]
It looks like [tags are automatically zipped](https://github.com/SublimeText/PowerShell/tags).

Also, you can use it un-zipped in a `PowerShell` directory inside your `Packages` folder (as opposed to `Installed Packages` which wants the zipped `.sublime-package`s), which is also true of almost every other Sublime Text package.

**Comment by blazer2k1** [comment]
Thanks @michaelblyons I got it working now by packaging the Support folder only.
