### ISSUE TITLE
Now what?

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [SublimeText/PowerShell#176]
So I installed it. Now what? There is no right click like Terminus and Terminal. In fact no sign of it anywhere???

**Comment by michaelblyons** [comment]
Now you have syntax highlighting, comment toggling, a build system for non-interactive scripts, and (if you want it) a silly color scheme that pretends to be an old Powershell palette.

If you would like to use scopes for your syntax highlighting that more closely match the Sublime Text built-in languages, you can [use the pre-release](https://github.com/SublimeText/PowerShell/blob/master/messages/prerelease-invitation.md) version.

If you want to set up a build system that points to one of Terminus's terminal emulator options, you'll have to ask the Terminus people for help.
