### ISSUE TITLE
How do I get 3.1.0 back?

### ISSUE THREAD

**Issue by mjr4077au** [SublimeText/PowerShell#179]
This new release completely changes the colour of everything, and at first glance I thought I left a quote off the end of a string or something. Even automatic variables have no colour consistency between them:

![image](https://github.com/user-attachments/assets/5f04cb43-7aca-4f4c-a99a-d2354ed2a586)

Do you have an offline download as all I can see is one single release for 4.0.0...

**Comment by michaelblyons** [comment]
You can download any commit from GitHub with `github.com/{user}/{repo}/archive/{refspec}.zip`. Rename the zip to `PowerShell.sublime-package` and put it in Sublime Text's "Installed Packages" folder.

**Comment by deathaxe** [comment]
Naah. Need to unpack it as they contain an additional level of folders, which might cause issues.

**Comment by mjr4077au** [comment]
Thanks for this, I actually managed to recover a cached copy from another machine I had. Placed it in and changed the NTFS permissions to prevent deletion or writing to the file 🥳. Merry Christmas!
