### ISSUE TITLE
Build requires -Name option for Import-Module

### ISSUE THREAD

**Issue by frizop** [SublimeText/PowerShell#18]
For some reason I can not Import-Module AWSPowerShell, I must
Import-Module -Name "C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.dll"

I've also tried to remove the -noprofile from the build script and that didn't work either. Is this known, or would you happen to know why? When I run the same script from my local powershell, using -noprofile -file C:\foo.ps1 the script works as expected. When running the script via the CTRL+B from within sublime I get the following output:

Import-Module : The specified module 'AWSPowerShell' was not loaded because no 
valid module file was found in any module directory.

Edit: I tried removing the -noprofile again and think that resolved it. I'm not totally sure what's going on but it appeared that my $env:psmodulepath was wrong.. again I think this was something on my end and this can likely be closed

**Comment by vors** [comment]
Interesting. I didn't know about `Ctrl+B` at all.
@guillermooo , should we move all related effort to https://github.com/guillermooo/PowerShellConsole ?

**Comment by vors** [comment]
Closing old issues, let's open a new one if it's still a problem.
