### ISSUE TITLE
Here Strings with single quotes

### ISSUE THREAD

**Issue by ptseng** [SublimeText/PowerShell#20]
There seems to be a problem with syntax highlighting for Powershell Here strings.

    @”

    Sample Text

    “@  | Sample-Command  

Seems to format correctly.

However,

    @’

    Sample Text

    ‘@ | Sample-Command

Does not.

**Comment by vors** [comment]
Since github use the same grammar, we can test it here:

```powershell
@"

Sample Text

"@  | Sample-Command  
```

```powershell
@'

Sample Text

'@  | Sample-Command  
```

**Comment by ptseng** [comment]
Thank you.
