### ISSUE TITLE
exclude dev-files from end-user distro

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PowerShell#45]
Provided that we are ok with giving up the `master` branch for development (i. e., its sole purpose is to mark stable releases):

Before each release, we would create a `temp-release` branch forking `dev`, delete the development files there, and merge `temp-release` with `master`. (Just an example, the process may be further streamlined.)

**Comment by vors** [comment]
This is not applicable anymore, we switched to a single `master` that serves for distribution. The development is done in https://github.com/PowerShell/EditorSyntax
