### ISSUE TITLE
Chained Methods/Properties Should Look the Same

### ISSUE THREAD

**Issue by bcrotty** [SublimeText/PowerShell#77]
![2015-01-28 17_01_31-c__users_bcrotty_skydrive_script archive_office 365 create and license users vi](https://cloud.githubusercontent.com/assets/6155964/5949018/5f628314-a70f-11e4-818d-fe0b1efad616.png)

**Comment by vors** [comment]
I believe it's the same issue is #66

**Comment by vors** [comment]
Moved to https://github.com/PowerShell/EditorSyntax/issues/107
