### ISSUE TITLE
Clean Up Snippet Formatting and Duplicates

### ISSUE THREAD

**Issue by bcrotty** [SublimeText/PowerShell#83]
Only one of the snippets includes a description tag, so most are using the file name for the name of the snippet, but even the file names are not all consistent. Also, the expanded text is not always formatted properly, such as the ```Set-PSDebug``` snippet, which should be capitalized as shown.

**Comment by vors** [comment]
Can you give an example? Does it relate to #81?

**Comment by bcrotty** [comment]
I fixed all the issues I found in the commit https://github.com/bcrotty/PowerShell/commit/daeb3d007c61acc3e170cb6617be44e959abcded

**Comment by vors** [comment]
Waiting  for pull requests from you :)

**Comment by bcrotty** [comment]
Sorry. Still getting used to Git/GitHub. If I do a pull request can I do it in such a way that it only compares certain files or will it compare the whole thing?

**Comment by vors** [comment]
It will compare the whole thing.
I would recommend you this reading http://nvie.com/posts/a-successful-git-branching-model/
Bottom-line: one branch per feature. Then PR to `dev` branch in `origin` (by origin, I always mean this repo).

To localize your changes in current situation, you can start new branch from `origin/dev` and cherry-pick commits that you want. There are other options to do that.

Don't hesitate to ask, if you have problems with git.

**Comment by bcrotty** [comment]
Merged with #90.
