### ISSUE TITLE
Parsing of specific $() sequence breaks syntax highlighting for rest of file

### ISSUE THREAD

**Issue by scottbilas** [SublimeText/PowerShell#87]
A very specific $() sequence causes the end of a string to not get recognized, which breaks syntax highlighting for all following code. This really needs to be explained with pictures. I have narrowed down the use case to this:

```powershell
	foo "$(x).exe"

	function blah() {
	    $blah = 'blah' # comment
	}
```

Which looks like this:

![image](https://cloud.githubusercontent.com/assets/964720/6209865/53766420-b5ca-11e4-8605-84effbb7f4ca.png)

Whereas it really ought to look like this:

![image](https://cloud.githubusercontent.com/assets/964720/6209879/7804a23e-b5ca-11e4-85fa-fa54127259ab.png)

The correct syntax highlighting can be restored any number of ways:

  * Commenting out the top line with #
  * Changing "exe" to anything else (as I've done in the second screen shot). For example, 'xexe' or 'e'.
  * Putting an extra double quote at the end of the line, or on a following line
  * Messing around with the location of the parens.

Some kind of pathological case for whatever rx's are operating underneath has been hit.

I've been able to work around the issue by using an -f formatter rather than string interpolation.

This is with v2015.01.27.08.27.14.

**Comment by vors** [comment]
Thank you for reporting this!
I think I just created a duplicate #95

**Comment by vors** [comment]
Fixed in https://github.com/SublimeText/PowerShell/pull/96
