### ISSUE TITLE
prototype to run PS code from Sublime Text

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PowerShell#89]
Discussion started in #78 

I'll try to start work on a prototype server to run PS code from a custom runspace. The server will most probably be written in F# and communicate with ST via pipes.

**Comment by vors** [comment]
.NET pipes?

**Comment by guillermooo** [comment]
Nope, just output redirection.

**Comment by vors** [comment]
oh, got it :) I used WCF recently and keep thinking about its pipes.

**Comment by guillermooo** [comment]
But we can try using a named pipe.

**Comment by vors** [comment]
We decided to do this work in a separate repo.
https://github.com/guillermooo/PowerShellConsole
