### ISSUE TITLE
integrate with new static analyzer for PowerShell

### ISSUE THREAD

**Issue by guillermooo** [SublimeText/PowerShell#94]
Announced by the PS Team in their blog.

**Comment by vors** [comment]
`PSScriptAnalyzer` I believe. That's an awesome feature proposal.
Blog post for reference http://blogs.msdn.com/b/powershell/archive/2015/02/24/powershell-script-analyzer-static-code-analysis-for-windows-powershell-scripts-amp-modules.aspx

**Comment by vors** [comment]
I just tried it on the real world codebase and it's very far from useful.
Won't fix for now.
